version: "3"

services:
  slave:
    container_name: slave
    image: mysql:5.7
    links:
      - master:master
    command: '--default-authentication-plugin=mysql_native_password --server_id=2 --relay_log=mysql-relay-bin --read_only=1'
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - master
    ports:
      - 13311:3306

  master:
    container_name: master
    image: mariadb:10
    command: '--default-authentication-plugin=mysql_native_password --log_bin=mysql-bin --server_id=10 --sync_binlog=1'
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 13312:3306

